#!/usr/bin/env python3
"""Generate a production-oriented .env file for docker-compose deployment."""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path


def build_env_text() -> str:
    postgres_db = "sms_assistant"
    postgres_user = "sms_assistant"
    postgres_password = secrets.token_urlsafe(24)
    flask_secret_key = secrets.token_urlsafe(48)
    database_url = (
        f"postgresql://{postgres_user}:{postgres_password}@postgres:5432/{postgres_db}"
    )

    lines = [
        "# Generated by generate_env.py",
        "# Fill OPENAI_API_KEY before starting the application.",
        "",
        "# Flask",
        "FLASK_ENV=production",
        f"FLASK_SECRET_KEY={flask_secret_key}",
        "",
        "# PostgreSQL",
        f"POSTGRES_DB={postgres_db}",
        f"POSTGRES_USER={postgres_user}",
        f"POSTGRES_PASSWORD={postgres_password}",
        f"DATABASE_URL={database_url}",
        "",
        "# OpenAI API",
        "OPENAI_API_KEY=",
        "OPENAI_TEXT_MODEL=gpt-5",
        "OPENAI_IMAGE_MODEL=dall-e-3",
        "",
        "# Additional settings",
        "LOG_LEVEL=INFO",
        "MAX_RETRIES=3",
        "TIMEOUT=30",
        "VK_API_VERSION=5.139",
        "",
        "# Legacy script compatibility",
        "VK_TOKEN=",
        "VK_GROUP_ID=",
        "TG_TOKEN=",
        "TG_CHAT_ID=",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a .env file for deployment.")
    parser.add_argument("--output", default=".env", help="Path to the output file")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output file if it already exists",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the generated content instead of writing a file",
    )
    args = parser.parse_args()

    env_text = build_env_text()

    if args.stdout:
        print(env_text, end="")
        return 0

    output_path = Path(args.output)
    if output_path.exists() and not args.force:
        raise SystemExit(
            f"Refusing to overwrite existing file: {output_path}. Use --force to replace it."
        )

    output_path.write_text(env_text, encoding="utf-8")
    print(f"Generated {output_path}. Fill OPENAI_API_KEY before deploy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
